---
name: main

on:
  push:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_REPO: acestream-engine

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup
        run: ./setup.sh
      - name: test
        run: ./test.sh
      - name: Setup tmate session
        if: ${{ github.event_name == 'workflow_dispatch' &&
                github.event.inputs.debug_enabled ||
                failure() }}
        uses: mxschmitt/action-tmate@v3

  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy acestream-engine
        env:
          TAG: ${{ github.ref_name }}
          ENDPOINT: ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}/actions/workflows/main.yml"
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./deploy.sh
