---
name: main

on:
  push:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_REPO: acestream-engine

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup
        run: ./setup.sh
      - name: test
        run: ./test.sh
      - name: Setup tmate session
        if: ${{ github.event_name == 'workflow_dispatch' &&
                github.event.inputs.debug_enabled ||
                failure() }}
        uses: mxschmitt/action-tmate@v3
      - name: deploy
        if: startswith(github.ref, 'refs/tags/')
        env:
          TAG: ${{ github.ref_name }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          ENDPOINT: ${{ secrets.DOCKER_USERNAME }}/acestream-service/actions/workflows/main.yml
          TOKEN: ${{ secrets.ACESTREAM_SERVICE_TOKEN }}
        run: ./deploy.sh
